version: "3.9"

services:
  backend:
    build: ./backend
    container_name: gestfacture-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:mysql://mysql-3f2a328e-riyadmaj10-0380.b.aivencloud.com:14484/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci"
      DB_USERNAME: "avnadmin"
      DB_PASSWORD: "AVNS_v0CTPDpEzEsSbNrVzle"
